export const navigation = [
  {
    title: 'Introduction',
    links: [
      { title: 'Getting started', href: '/' },
      { title: 'Installation', href: '/docs/installation' },
      { title: 'Core concepts', href: '/docs/core-concepts' },
    ],
  },
  {
    title: 'Guides',
    links: [
      { title: 'Query builder basics', href: '/docs/query-builder' },
      { title: 'TypeScript integration', href: '/docs/typescript' },
      { title: 'Direct data access', href: '/docs/direct-data' },
      { title: 'Image assets', href: '/docs/images' },
      { title: 'Search utility', href: '/docs/search' },
      { title: 'Quality calculator', href: '/docs/calculator' },
      { title: 'Save file parser', href: '/docs/save-parser' },
    ],
  },
  {
    title: 'Farming & Foraging',
    links: [
      { title: 'Crops', href: '/docs/crops' },
      { title: 'Trees', href: '/docs/trees' },
      { title: 'Forageables', href: '/docs/forageables' },
      { title: 'Mixed seeds', href: '/docs/mixed-seeds' },
      { title: 'Animals', href: '/docs/animals' },
      { title: 'Artisan goods', href: '/docs/artisan-goods' },
      { title: 'Seasons & weather', href: '/docs/seasons-weather' },
    ],
  },
  {
    title: 'Fishing & Mining',
    links: [
      { title: 'Fish', href: '/docs/fish' },
      { title: 'Bait & tackle', href: '/docs/bait-tackle' },
      { title: 'Minerals', href: '/docs/minerals' },
      { title: 'Artifacts', href: '/docs/artifacts' },
    ],
  },
  {
    title: 'Characters & Social',
    links: [
      { title: 'Villagers', href: '/docs/villagers' },
      { title: 'Universal gifts', href: '/docs/universal-gifts' },
      { title: 'Events', href: '/docs/events' },
      { title: 'Quests', href: '/docs/quests' },
      { title: 'Special orders', href: '/docs/special-orders' },
    ],
  },
  {
    title: 'Skills & Progression',
    links: [
      { title: 'Skills', href: '/docs/skills' },
      { title: 'Professions', href: '/docs/professions' },
      { title: 'Achievements', href: '/docs/achievements' },
      { title: 'Perfection', href: '/docs/perfection' },
      { title: "Grandpa's evaluation", href: '/docs/grandpa' },
      { title: 'Stardrops', href: '/docs/stardrops' },
    ],
  },
  {
    title: 'Combat',
    links: [
      { title: 'Monsters', href: '/docs/monsters' },
      { title: 'Monster loot', href: '/docs/monster-loot' },
      { title: 'Monster slayer goals', href: '/docs/monster-slayer-goals' },
      { title: 'Weapons & weapon stats', href: '/docs/weapons' },
      { title: 'Rings', href: '/docs/rings' },
      { title: 'Trinkets', href: '/docs/trinkets' },
    ],
  },
  {
    title: 'Equipment & Items',
    links: [
      { title: 'Tools', href: '/docs/tools' },
      { title: 'Footwear', href: '/docs/footwear' },
      { title: 'Hats', href: '/docs/hats' },
      { title: 'Special items', href: '/docs/special-items' },
    ],
  },
  {
    title: 'Buildings & Locations',
    links: [
      { title: 'Buildings', href: '/docs/buildings' },
      { title: 'Farmhouse', href: '/docs/farmhouse' },
      { title: 'Locations', href: '/docs/locations' },
      { title: 'Maps', href: '/docs/maps' },
      { title: 'Golden walnuts', href: '/docs/golden-walnuts' },
      { title: 'Field office', href: '/docs/field-office' },
    ],
  },
  {
    title: 'Collections & Knowledge',
    links: [
      { title: 'Bundles', href: '/docs/bundles' },
      { title: 'Collections', href: '/docs/collections' },
      { title: 'Lost books', href: '/docs/lost-books' },
      { title: 'Secret notes', href: '/docs/secret-notes' },
      { title: 'Concessions', href: '/docs/concessions' },
      { title: 'Cooking', href: '/docs/cooking' },
      { title: 'Crafting', href: '/docs/crafting' },
    ],
  },
  {
    title: 'Shops',
    links: [
      { title: 'Shops overview', href: '/docs/shops' },
      { title: 'Blacksmith', href: '/docs/shops-blacksmith' },
      { title: 'Bookseller', href: '/docs/shops-bookseller' },
      { title: 'Carpenter', href: '/docs/shops-carpenter' },
      { title: 'Casino', href: '/docs/shops-casino' },
      { title: 'Desert trader', href: '/docs/shops-desert-trader' },
      { title: 'Dwarf', href: '/docs/shops-dwarf' },
      { title: "Adventurer's guild", href: '/docs/shops-guild' },
      { title: 'Island trader', href: '/docs/shops-island-trader' },
      { title: 'Joja mart', href: '/docs/shops-joja' },
      { title: 'Krobus', href: '/docs/shops-krobus' },
      { title: "Marnie's ranch", href: '/docs/shops-marnie' },
      { title: 'Medical supplies', href: '/docs/shops-medical-supplies' },
      { title: 'Oasis', href: '/docs/shops-oasis' },
      { title: "Pierre's", href: '/docs/shops-pierre' },
      { title: "Qi's walnut room", href: '/docs/shops-qi' },
      { title: 'Saloon', href: '/docs/shops-saloon' },
      { title: 'Volcano', href: '/docs/shops-volcano' },
      { title: "Willy's fish shop", href: '/docs/shops-willy' },
      { title: "Wizard's tower", href: '/docs/shops-wizard' },
    ],
  },
]
